package com.mycompany.mavenpails2;
/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import javax.annotation.Generated;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
@Generated(value = "Autogenerated by Thrift Compiler (0.9.2)", date = "2015-6-16")
public class Position implements org.apache.thrift.TBase<Position, Position._Fields>, java.io.Serializable, Cloneable, Comparable<Position> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("Position");

  private static final org.apache.thrift.protocol.TField POSX_FIELD_DESC = new org.apache.thrift.protocol.TField("posx", org.apache.thrift.protocol.TType.I32, (short)1);
  private static final org.apache.thrift.protocol.TField POSY_FIELD_DESC = new org.apache.thrift.protocol.TField("posy", org.apache.thrift.protocol.TType.I32, (short)2);
  private static final org.apache.thrift.protocol.TField POSZ_FIELD_DESC = new org.apache.thrift.protocol.TField("posz", org.apache.thrift.protocol.TType.I32, (short)3);
  private static final org.apache.thrift.protocol.TField EJE1_FIELD_DESC = new org.apache.thrift.protocol.TField("eje1", org.apache.thrift.protocol.TType.I32, (short)4);
  private static final org.apache.thrift.protocol.TField EJE2_FIELD_DESC = new org.apache.thrift.protocol.TField("eje2", org.apache.thrift.protocol.TType.I32, (short)5);
  private static final org.apache.thrift.protocol.TField ELEVACION_FIELD_DESC = new org.apache.thrift.protocol.TField("elevacion", org.apache.thrift.protocol.TType.I32, (short)6);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new PositionStandardSchemeFactory());
    schemes.put(TupleScheme.class, new PositionTupleSchemeFactory());
  }

  public int posx; // required
  public int posy; // required
  public int posz; // required
  public int eje1; // required
  public int eje2; // required
  public int elevacion; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    POSX((short)1, "posx"),
    POSY((short)2, "posy"),
    POSZ((short)3, "posz"),
    EJE1((short)4, "eje1"),
    EJE2((short)5, "eje2"),
    ELEVACION((short)6, "elevacion");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // POSX
          return POSX;
        case 2: // POSY
          return POSY;
        case 3: // POSZ
          return POSZ;
        case 4: // EJE1
          return EJE1;
        case 5: // EJE2
          return EJE2;
        case 6: // ELEVACION
          return ELEVACION;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __POSX_ISSET_ID = 0;
  private static final int __POSY_ISSET_ID = 1;
  private static final int __POSZ_ISSET_ID = 2;
  private static final int __EJE1_ISSET_ID = 3;
  private static final int __EJE2_ISSET_ID = 4;
  private static final int __ELEVACION_ISSET_ID = 5;
  private byte __isset_bitfield = 0;
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.POSX, new org.apache.thrift.meta_data.FieldMetaData("posx", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.POSY, new org.apache.thrift.meta_data.FieldMetaData("posy", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.POSZ, new org.apache.thrift.meta_data.FieldMetaData("posz", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.EJE1, new org.apache.thrift.meta_data.FieldMetaData("eje1", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.EJE2, new org.apache.thrift.meta_data.FieldMetaData("eje2", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.ELEVACION, new org.apache.thrift.meta_data.FieldMetaData("elevacion", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(Position.class, metaDataMap);
  }

  public Position() {
  }

  public Position(
    int posx,
    int posy,
    int posz,
    int eje1,
    int eje2,
    int elevacion)
  {
    this();
    this.posx = posx;
    setPosxIsSet(true);
    this.posy = posy;
    setPosyIsSet(true);
    this.posz = posz;
    setPoszIsSet(true);
    this.eje1 = eje1;
    setEje1IsSet(true);
    this.eje2 = eje2;
    setEje2IsSet(true);
    this.elevacion = elevacion;
    setElevacionIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public Position(Position other) {
    __isset_bitfield = other.__isset_bitfield;
    this.posx = other.posx;
    this.posy = other.posy;
    this.posz = other.posz;
    this.eje1 = other.eje1;
    this.eje2 = other.eje2;
    this.elevacion = other.elevacion;
  }

  public Position deepCopy() {
    return new Position(this);
  }

  @Override
  public void clear() {
    setPosxIsSet(false);
    this.posx = 0;
    setPosyIsSet(false);
    this.posy = 0;
    setPoszIsSet(false);
    this.posz = 0;
    setEje1IsSet(false);
    this.eje1 = 0;
    setEje2IsSet(false);
    this.eje2 = 0;
    setElevacionIsSet(false);
    this.elevacion = 0;
  }

  public int getPosx() {
    return this.posx;
  }

  public Position setPosx(int posx) {
    this.posx = posx;
    setPosxIsSet(true);
    return this;
  }

  public void unsetPosx() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __POSX_ISSET_ID);
  }

  /** Returns true if field posx is set (has been assigned a value) and false otherwise */
  public boolean isSetPosx() {
    return EncodingUtils.testBit(__isset_bitfield, __POSX_ISSET_ID);
  }

  public void setPosxIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __POSX_ISSET_ID, value);
  }

  public int getPosy() {
    return this.posy;
  }

  public Position setPosy(int posy) {
    this.posy = posy;
    setPosyIsSet(true);
    return this;
  }

  public void unsetPosy() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __POSY_ISSET_ID);
  }

  /** Returns true if field posy is set (has been assigned a value) and false otherwise */
  public boolean isSetPosy() {
    return EncodingUtils.testBit(__isset_bitfield, __POSY_ISSET_ID);
  }

  public void setPosyIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __POSY_ISSET_ID, value);
  }

  public int getPosz() {
    return this.posz;
  }

  public Position setPosz(int posz) {
    this.posz = posz;
    setPoszIsSet(true);
    return this;
  }

  public void unsetPosz() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __POSZ_ISSET_ID);
  }

  /** Returns true if field posz is set (has been assigned a value) and false otherwise */
  public boolean isSetPosz() {
    return EncodingUtils.testBit(__isset_bitfield, __POSZ_ISSET_ID);
  }

  public void setPoszIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __POSZ_ISSET_ID, value);
  }

  public int getEje1() {
    return this.eje1;
  }

  public Position setEje1(int eje1) {
    this.eje1 = eje1;
    setEje1IsSet(true);
    return this;
  }

  public void unsetEje1() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __EJE1_ISSET_ID);
  }

  /** Returns true if field eje1 is set (has been assigned a value) and false otherwise */
  public boolean isSetEje1() {
    return EncodingUtils.testBit(__isset_bitfield, __EJE1_ISSET_ID);
  }

  public void setEje1IsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __EJE1_ISSET_ID, value);
  }

  public int getEje2() {
    return this.eje2;
  }

  public Position setEje2(int eje2) {
    this.eje2 = eje2;
    setEje2IsSet(true);
    return this;
  }

  public void unsetEje2() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __EJE2_ISSET_ID);
  }

  /** Returns true if field eje2 is set (has been assigned a value) and false otherwise */
  public boolean isSetEje2() {
    return EncodingUtils.testBit(__isset_bitfield, __EJE2_ISSET_ID);
  }

  public void setEje2IsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __EJE2_ISSET_ID, value);
  }

  public int getElevacion() {
    return this.elevacion;
  }

  public Position setElevacion(int elevacion) {
    this.elevacion = elevacion;
    setElevacionIsSet(true);
    return this;
  }

  public void unsetElevacion() {
    __isset_bitfield = EncodingUtils.clearBit(__isset_bitfield, __ELEVACION_ISSET_ID);
  }

  /** Returns true if field elevacion is set (has been assigned a value) and false otherwise */
  public boolean isSetElevacion() {
    return EncodingUtils.testBit(__isset_bitfield, __ELEVACION_ISSET_ID);
  }

  public void setElevacionIsSet(boolean value) {
    __isset_bitfield = EncodingUtils.setBit(__isset_bitfield, __ELEVACION_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case POSX:
      if (value == null) {
        unsetPosx();
      } else {
        setPosx((Integer)value);
      }
      break;

    case POSY:
      if (value == null) {
        unsetPosy();
      } else {
        setPosy((Integer)value);
      }
      break;

    case POSZ:
      if (value == null) {
        unsetPosz();
      } else {
        setPosz((Integer)value);
      }
      break;

    case EJE1:
      if (value == null) {
        unsetEje1();
      } else {
        setEje1((Integer)value);
      }
      break;

    case EJE2:
      if (value == null) {
        unsetEje2();
      } else {
        setEje2((Integer)value);
      }
      break;

    case ELEVACION:
      if (value == null) {
        unsetElevacion();
      } else {
        setElevacion((Integer)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case POSX:
      return Integer.valueOf(getPosx());

    case POSY:
      return Integer.valueOf(getPosy());

    case POSZ:
      return Integer.valueOf(getPosz());

    case EJE1:
      return Integer.valueOf(getEje1());

    case EJE2:
      return Integer.valueOf(getEje2());

    case ELEVACION:
      return Integer.valueOf(getElevacion());

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case POSX:
      return isSetPosx();
    case POSY:
      return isSetPosy();
    case POSZ:
      return isSetPosz();
    case EJE1:
      return isSetEje1();
    case EJE2:
      return isSetEje2();
    case ELEVACION:
      return isSetElevacion();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof Position)
      return this.equals((Position)that);
    return false;
  }

  public boolean equals(Position that) {
    if (that == null)
      return false;

    boolean this_present_posx = true;
    boolean that_present_posx = true;
    if (this_present_posx || that_present_posx) {
      if (!(this_present_posx && that_present_posx))
        return false;
      if (this.posx != that.posx)
        return false;
    }

    boolean this_present_posy = true;
    boolean that_present_posy = true;
    if (this_present_posy || that_present_posy) {
      if (!(this_present_posy && that_present_posy))
        return false;
      if (this.posy != that.posy)
        return false;
    }

    boolean this_present_posz = true;
    boolean that_present_posz = true;
    if (this_present_posz || that_present_posz) {
      if (!(this_present_posz && that_present_posz))
        return false;
      if (this.posz != that.posz)
        return false;
    }

    boolean this_present_eje1 = true;
    boolean that_present_eje1 = true;
    if (this_present_eje1 || that_present_eje1) {
      if (!(this_present_eje1 && that_present_eje1))
        return false;
      if (this.eje1 != that.eje1)
        return false;
    }

    boolean this_present_eje2 = true;
    boolean that_present_eje2 = true;
    if (this_present_eje2 || that_present_eje2) {
      if (!(this_present_eje2 && that_present_eje2))
        return false;
      if (this.eje2 != that.eje2)
        return false;
    }

    boolean this_present_elevacion = true;
    boolean that_present_elevacion = true;
    if (this_present_elevacion || that_present_elevacion) {
      if (!(this_present_elevacion && that_present_elevacion))
        return false;
      if (this.elevacion != that.elevacion)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    List<Object> list = new ArrayList<Object>();

    boolean present_posx = true;
    list.add(present_posx);
    if (present_posx)
      list.add(posx);

    boolean present_posy = true;
    list.add(present_posy);
    if (present_posy)
      list.add(posy);

    boolean present_posz = true;
    list.add(present_posz);
    if (present_posz)
      list.add(posz);

    boolean present_eje1 = true;
    list.add(present_eje1);
    if (present_eje1)
      list.add(eje1);

    boolean present_eje2 = true;
    list.add(present_eje2);
    if (present_eje2)
      list.add(eje2);

    boolean present_elevacion = true;
    list.add(present_elevacion);
    if (present_elevacion)
      list.add(elevacion);

    return list.hashCode();
  }

  @Override
  public int compareTo(Position other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetPosx()).compareTo(other.isSetPosx());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPosx()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.posx, other.posx);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPosy()).compareTo(other.isSetPosy());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPosy()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.posy, other.posy);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetPosz()).compareTo(other.isSetPosz());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPosz()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.posz, other.posz);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetEje1()).compareTo(other.isSetEje1());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEje1()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.eje1, other.eje1);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetEje2()).compareTo(other.isSetEje2());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEje2()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.eje2, other.eje2);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetElevacion()).compareTo(other.isSetElevacion());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetElevacion()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.elevacion, other.elevacion);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("Position(");
    boolean first = true;

    sb.append("posx:");
    sb.append(this.posx);
    first = false;
    if (!first) sb.append(", ");
    sb.append("posy:");
    sb.append(this.posy);
    first = false;
    if (!first) sb.append(", ");
    sb.append("posz:");
    sb.append(this.posz);
    first = false;
    if (!first) sb.append(", ");
    sb.append("eje1:");
    sb.append(this.eje1);
    first = false;
    if (!first) sb.append(", ");
    sb.append("eje2:");
    sb.append(this.eje2);
    first = false;
    if (!first) sb.append(", ");
    sb.append("elevacion:");
    sb.append(this.elevacion);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class PositionStandardSchemeFactory implements SchemeFactory {
    public PositionStandardScheme getScheme() {
      return new PositionStandardScheme();
    }
  }

  private static class PositionStandardScheme extends StandardScheme<Position> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, Position struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // POSX
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.posx = iprot.readI32();
              struct.setPosxIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // POSY
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.posy = iprot.readI32();
              struct.setPosyIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // POSZ
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.posz = iprot.readI32();
              struct.setPoszIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // EJE1
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.eje1 = iprot.readI32();
              struct.setEje1IsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // EJE2
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.eje2 = iprot.readI32();
              struct.setEje2IsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // ELEVACION
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.elevacion = iprot.readI32();
              struct.setElevacionIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, Position struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(POSX_FIELD_DESC);
      oprot.writeI32(struct.posx);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(POSY_FIELD_DESC);
      oprot.writeI32(struct.posy);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(POSZ_FIELD_DESC);
      oprot.writeI32(struct.posz);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(EJE1_FIELD_DESC);
      oprot.writeI32(struct.eje1);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(EJE2_FIELD_DESC);
      oprot.writeI32(struct.eje2);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(ELEVACION_FIELD_DESC);
      oprot.writeI32(struct.elevacion);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class PositionTupleSchemeFactory implements SchemeFactory {
    public PositionTupleScheme getScheme() {
      return new PositionTupleScheme();
    }
  }

  private static class PositionTupleScheme extends TupleScheme<Position> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, Position struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetPosx()) {
        optionals.set(0);
      }
      if (struct.isSetPosy()) {
        optionals.set(1);
      }
      if (struct.isSetPosz()) {
        optionals.set(2);
      }
      if (struct.isSetEje1()) {
        optionals.set(3);
      }
      if (struct.isSetEje2()) {
        optionals.set(4);
      }
      if (struct.isSetElevacion()) {
        optionals.set(5);
      }
      oprot.writeBitSet(optionals, 6);
      if (struct.isSetPosx()) {
        oprot.writeI32(struct.posx);
      }
      if (struct.isSetPosy()) {
        oprot.writeI32(struct.posy);
      }
      if (struct.isSetPosz()) {
        oprot.writeI32(struct.posz);
      }
      if (struct.isSetEje1()) {
        oprot.writeI32(struct.eje1);
      }
      if (struct.isSetEje2()) {
        oprot.writeI32(struct.eje2);
      }
      if (struct.isSetElevacion()) {
        oprot.writeI32(struct.elevacion);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, Position struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(6);
      if (incoming.get(0)) {
        struct.posx = iprot.readI32();
        struct.setPosxIsSet(true);
      }
      if (incoming.get(1)) {
        struct.posy = iprot.readI32();
        struct.setPosyIsSet(true);
      }
      if (incoming.get(2)) {
        struct.posz = iprot.readI32();
        struct.setPoszIsSet(true);
      }
      if (incoming.get(3)) {
        struct.eje1 = iprot.readI32();
        struct.setEje1IsSet(true);
      }
      if (incoming.get(4)) {
        struct.eje2 = iprot.readI32();
        struct.setEje2IsSet(true);
      }
      if (incoming.get(5)) {
        struct.elevacion = iprot.readI32();
        struct.setElevacionIsSet(true);
      }
    }
  }

}

